"""Accept a user-supplied ScubaGear file and run the real pipeline over it.

Why this matters beyond convenience: without it, "we used CISA's published
sample" and "it only works on the one file we had" are indistinguishable from
the outside. Letting someone drop in their own scan is the only way to
*demonstrate* that the pipeline generalises rather than asserting it.

There is no separate code path for uploaded data. It runs the same parser, the
same transformers and the same validator as ``scripts/generate.py``. If the
upload produces eight valid OSCAL documents, that is the same claim we make
about the sample.

**Untrusted input.** A ScubaGear file is generated by a scanner, but by the
time it reaches us it is a file a person chose to hand over, and its free-text
fields (``Requirement``, ``Details``) end up in an agent's context. Those fields
are therefore treated as data, never as instructions -- see
:func:`sanitise_free_text`.
"""

from __future__ import annotations

import json
import re
import tempfile
from dataclasses import dataclass
from pathlib import Path

from ..parsers.scubagear import parse_run
from ..pipeline import generate
from ..validation import validate_file

#: A ScubaGear results file is ~2 MB. Anything far larger is not one.
MAX_UPLOAD_BYTES = 25 * 1024 * 1024

#: Phrases that address a model rather than describe a control. Neutralised
#: rather than removed, so tampering stays visible to whoever reads the artifact.
#:
#: Deliberately narrow. An earlier version matched a bare "system prompt", which
#: flagged the legitimate baseline sentence "The system prompts the user for
#: MFA". Mangling real compliance text is a correctness failure and is worse
#: than missing an exotic phrasing -- especially since this is defence in depth,
#: not the primary control. The primary control is architectural: agents state
#: facts only via tools over validated artifacts, so injected prose has no path
#: to become a compliance claim.
_INJECTION = re.compile(
    r"(ignore\s+(all\s+)?(previous|prior|above)\s+instructions?"
    r"|disregard\s+(the\s+)?(previous|prior|above)\s+(instructions?|text|content)"
    r"|you\s+are\s+now\s+(a|an|the)\s"
    r"|(your|the)\s+system\s+prompt\b"   # \b so "prompts" (a verb) is not caught
    r"|<\s*/?\s*(system|assistant|tool)\s*>)",
    re.IGNORECASE,
)


def sanitise_free_text(text: str) -> str:
    """Neutralise text that tries to issue instructions to a model.

    We do not silently drop it: a compliance artifact should record what the
    input actually said. The marker makes tampering obvious to a human reader
    while removing the imperative form a model might follow.
    """
    return _INJECTION.sub("[redacted: instruction-like text in scan data]", text or "")


@dataclass
class UploadResult:
    ok: bool
    message: str
    oscal_dir: Path | None = None
    tenant: str = ""
    policies: int = 0
    failures: int = 0
    documents: int = 0
    validated: int = 0
    injection_hits: int = 0


def _looks_like_scubagear(doc: dict) -> str | None:
    """Return an error message if this is not a ScubaGear results file."""
    missing = {"MetaData", "Results"} - doc.keys()
    if missing:
        return (
            f"This does not look like a ScubaGear results file — it is missing "
            f"{', '.join(sorted(missing))}. Expected a ScubaResults*.json produced "
            f"by ScubaGear. Found top-level keys: {', '.join(sorted(doc)[:6])}."
        )
    if not isinstance(doc["Results"], dict) or not doc["Results"]:
        return "The file has a Results section, but it is empty or not an object."
    return None


def process_upload(raw: bytes, baselines_path: Path, mappings_dir: Path) -> UploadResult:
    """Parse, transform and validate an uploaded ScubaGear file."""
    if len(raw) > MAX_UPLOAD_BYTES:
        return UploadResult(False, f"File is larger than {MAX_UPLOAD_BYTES // 1024 // 1024} MB.")

    try:
        # ScubaGear writes UTF-8 with a BOM; utf-8-sig handles both.
        doc = json.loads(raw.decode("utf-8-sig"))
    except UnicodeDecodeError:
        return UploadResult(False, "The file is not valid UTF-8 text.")
    except json.JSONDecodeError as exc:
        return UploadResult(False, f"The file is not valid JSON: {exc.msg} (line {exc.lineno}).")

    if not isinstance(doc, dict):
        return UploadResult(False, "Expected a JSON object at the top level.")

    problem = _looks_like_scubagear(doc)
    if problem:
        return UploadResult(False, problem)

    # Neutralise instruction-like text before anything reaches an agent.
    hits = 0
    for groups in doc["Results"].values():
        for group in groups or []:
            for control in group.get("Controls", []) or []:
                for field in ("Requirement", "Details"):
                    original = control.get(field)
                    if isinstance(original, str):
                        cleaned = sanitise_free_text(original)
                        if cleaned != original:
                            hits += 1
                            control[field] = cleaned

    workdir = Path(tempfile.mkdtemp(prefix="scuba-upload-"))
    source = workdir / "ScubaResults_uploaded.json"
    source.write_text(json.dumps(doc))

    try:
        run = parse_run(source)
    except Exception as exc:
        return UploadResult(False, f"Could not parse the assessment: {exc}")

    if not run.policies:
        return UploadResult(False, "The file parsed, but contains no assessed policies.")

    out = workdir / "oscal"
    try:
        written = generate(
            baselines_path=str(baselines_path),
            run_path=str(source),
            out_dir=str(out),
            crosswalk_path=str(mappings_dir / "scuba-to-nist-sp-800-53-r5-fedramp-high.csv"),
            migrations_path=str(mappings_dir / "scuba-baseline-policy-migrations.csv"),
        )
    except Exception as exc:
        return UploadResult(False, f"Generation failed: {exc}")

    # Validate with JSON Schema only: oscal-cli needs a JVM and several seconds
    # per document, which is too slow for an interactive upload. The CI gate
    # still runs the full validator.
    validated = sum(1 for path in written.values() if validate_file(path, use_cli=False).ok)

    return UploadResult(
        ok=True,
        message="Generated and validated.",
        oscal_dir=out,
        tenant=run.tenant_display_name or "uploaded tenant",
        policies=len(run.policies),
        failures=len(run.failures()),
        documents=len(written),
        validated=validated,
        injection_hits=hits,
    )
